variables:

  # Префикс таблиц
  tablesPrefix: ase_

  # Перечень сайтов
  sites:
    - url: https://prestonparkmuseum.co.uk/
      name: Preston park
    - url: https://dombulgakova.ru/
      name: Дом Булгакова
    - url: https://www.svetlovka.ru/
      name: Библиотека имени М. А. Светлова
    - url: https://nikoartgallery.com/
      name: Креативное пространство и галерея Н.Б. Никогосяна
    - url: https://et-cetera.ru/
      name: Московский театр «Et Cetera»

  #Свойства User Agent
  #userAgent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
  userAgent: another search engine bot
  referrer: http://www.google.com

  # Размер буферов для сохранения в БД
  pageBufferSize: 100
  lemmaBufferSize: 1000
  indexBufferSize: 5000

#Путь к веб-интерфейсу
server.servlet.context-path: /admin

# Свойства подключения к БД
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/search_engine_db
spring.datasource.username: bestuser
spring.datasource.password: bestuser

#Режим работы БД (create - для создания таблиц в БД, none - для обычной работы приложения)
spring.jpa.hibernate.ddl-auto: none